//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC_DevCpech.ContextDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAP_Programas_Matricula
    {
        public int Id_programa { get; set; }
        public string Nombre_programa { get; set; }
        public Nullable<int> Id_Modalidad { get; set; }
        public Nullable<int> Id_tipo_programa { get; set; }
        public Nullable<int> Id_tipo_programa_materiales_wired { get; set; }
        public Nullable<int> Cantidad_modulos { get; set; }
        public Nullable<int> Sincronico { get; set; }
        public Nullable<int> Cantidad_alumnos_sala { get; set; }
        public string Descripcion { get; set; }
        public string URL_ficha_Descriptiva { get; set; }
        public Nullable<System.DateTime> Fecha_registro { get; set; }
        public Nullable<int> Num_pagina { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<int> Programa { get; set; }
    
        public virtual CAP_Tipo_Programa CAP_Tipo_Programa { get; set; }
    }
}
