//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC_DevCpech.ContextDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAP_Modalidades
    {
        public int ID_modalidad { get; set; }
        public string Nombre_modalidad { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string urlfoto { get; set; }
    }
}
