//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC_DevCpech.ContextDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comunas
    {
        public int IdComuna { get; set; }
        public string NombreComuna { get; set; }
    }
}
