//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC_DevCpech.ContextDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlumnosEntities : DbContext
    {
        public AlumnosEntities()
            : base("name=AlumnosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comunas> Comunas { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<CAP_Modalidades> CAP_Modalidades { get; set; }
        public virtual DbSet<CAP_Programas_Matricula> CAP_Programas_Matricula { get; set; }
        public virtual DbSet<CAP_Tipo_Programa> CAP_Tipo_Programa { get; set; }
    }
}
